org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false
java_version=21

# Project
group=com.daqem.arc
version=9.2.0-PR1
mod_id=arc
mod_name=Arc
mod_description=Data driven action, reward, condition library for Minecraft NeoForge and Fabric
mod_author=DAQEM
mod_license=Apache-2.0
mod_website=https://daqem.com
mod_repository=https://github.com/DAQEM/ArcLib

# Publishing
supported_minecraft_versions=1.21.1
release_type=release
curse_forge_project_id=883593
curse_forge_dependencies=knot,ui,yaml-config
modrinth_project_id=H3eKhxi7
modrinth_dependencies=knot,ui-lib,yaml-config

# Dependencies
minecraft_version=1.21.1
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10
knot_version=9.1.0-PR2
uilib_version=9.1.0-PR1
yamlconfig_version=9.1.0-PR1

# Fabric
fabric_version=0.116.11+1.21.1
fabric_loader_version=0.19.2

# NeoForge
neoforge_version=21.1.228