modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mods]]
modId = "arc_test"
version = "1.0.0"
displayName = "Arc Test"
authors = "DAQEM"
description = '''
A test mod for the Arc library.
'''
license = "Apache-2.0"